### ISSUE TITLE
GridSearchCV no longer accepting multidimensional features

### ISSUE THREAD

**Issue by wd15** [openmaterials/pymks#132]
See GridSearchCV in http://openmaterials.github.io/pymks/rst/cahn_hilliard_Legendre.html as an example of where this is broken. The solution is to subclass GridSearchCV and flatten the array and then wrap the model class dynamically in a new class that unwrap the flatten data passed through GridSearchCV's fit method.

**Comment by davidbrough1** [comment]
Fixed with https://github.com/openmaterials/pymks/pull/134
