### ISSUE TITLE
correct make_cahn_hilliard initial microstructure values

### ISSUE THREAD

**Issue by davidbrough1** [openmaterials/pymks#137]
The initial microstructure values generated by the make_cahn_hilliard function come from an uniform distribution. They should come from a normal distribution with a small variance to more accurately represent the physical phenomenon.

**Comment by wd15** [comment]
I think it needs to be a uniform distribution to seed the model properly. The "make_cahn_hilliard" function is to create the data to calibrate the model, not to represent the physical phenomena correctly. The MKS model should be seeded with evenly distributed values over the grid to capture as many differences as possible between values. You may be right that when we are testing the model that we then need to use normal distributions, but using enough uniform distributions to calibrate the model should account for any particular initial condition.

It may also be possible to use normal distributions to calibrate the model but then we need to max and min at 1 and -1 and also vary the initial location of the distribution and the width of the distribution.
